app_version: 0.8.0
capabilities: []
categories:
- backup
date_added: '2026-07-27'
description: Scheduled backups of your TrueNAS system configuration, downloaded via
  the API.
home: https://github.com/CampAsAChamp/truenas-config-backup
host_mounts: []
icon: https://raw.githubusercontent.com/CampAsAChamp/truenas-config-backup/main/ix-dev/community/truenas-config-backup/icon.svg
keywords:
- backup
- config
- truenas
lib_version: 2.3.8
lib_version_hash: cd75c897a1e8fef54b5bd00d0d8849f240bc50db2ef650eccc0ee74f3b2b2dc1
maintainers:
- email: nickschneider101@gmail.com
  name: CampAsAChamp
  url: https://github.com/CampAsAChamp
name: truenas-config-backup
run_as_context:
- description: Container [truenas-config-backup] can run as any non-root user and
    group.
  gid: 568
  group_name: Host group is [apps]
  uid: 568
  user_name: Host user is [apps]
screenshots: []
sources:
- https://github.com/CampAsAChamp/truenas-config-backup
title: TrueNAS Config Backup
train: community
version: 1.0.0
