name: Test app

on:
  workflow_call:
    inputs:
      ref:
        description: Git ref to checkout
        required: false
        type: string
        default: ""

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref || github.sha }}
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - run: pip install -r requirements.txt -r requirements-dev.txt
      - run: ruff check app
      - run: pytest --cov
